version: '3.7'

services:

  morsid-dev:
    container_name: morsid-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - target: 3000
        published: 3001
        protocol: tcp
        mode: host
    environment:
      - CHOKIDAR_USEPOLLING=true
